### Register User
POST http://localhost:6767/auth/register
Content-Type: application/json

{
    "firstName" : "roti",
    "lastName" : "rumali",
    "email" : "rumaliroti@gmail.com",
    "password" : "kajukatli",
    "role" : "USER",
    "profileImageUrl" : "https://avatars.githubusercontent.com/u/118471720?v=4&size=64",
    "isUserActive" : true
}

### Login User (Auth)
POST http://localhost:6767/auth/login
Content-Type: application/json

{
    "email" : "rumaliroti@gmail.com",
    "password" : "kajukatli"
}

### Login User (Auth) change pass
PUT http://localhost:6767/auth/password
Content-Type: application/json

{
    "current_pass" : "kaju",
    "new_pass" : "kajukatli"
}

### /articles Fetch User articals
GET http://localhost:6767/user-api/articles

### /articles Fetch User articals by id
GET http://localhost:6767/user-api/article/

### add comments
PUT http://localhost:6767/user-api/comment/
Content-Type: application/json

{
    "article_id" : "69b4e06fb36981a7d4f122ae",
    "comment" : "L article!"
}

### Logout User (Auth)
GET http://localhost:6767/auth/logout